//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id_Producto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Precio { get; set; }
    }
}
