//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaFacturacionEntities : DbContext
    {
        public SistemaFacturacionEntities()
            : base("name=SistemaFacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TCliente> TClientes { get; set; }
        public virtual DbSet<TEntrada> TEntradas { get; set; }
        public virtual DbSet<TFacturacion> TFacturacions { get; set; }
        public virtual DbSet<TProducto> TProductoes { get; set; }
        public virtual DbSet<TProveedor> TProveedors { get; set; }
    }
}
