//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEntrada
    {
        public int Id_Entrada { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual TProducto TProducto { get; set; }
        public virtual TProveedor TProveedor { get; set; }
    }
}
