//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFactura
    {
        public int Id_Factura { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Total { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> ITBIS { get; set; }
    
        public virtual TCliente TCliente { get; set; }
    }
}
